// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.proto

package com.google.recaptchaenterprise.v1beta1;

public interface IOSKeySettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.recaptchaenterprise.v1beta1.IOSKeySettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * iOS bundle ids of apps allowed to use the key.
   * Example: 'com.companyname.productname.appname'
   * </pre>
   *
   * <code>repeated string allowed_bundle_ids = 1;</code>
   * @return A list containing the allowedBundleIds.
   */
  java.util.List<java.lang.String>
      getAllowedBundleIdsList();
  /**
   * <pre>
   * iOS bundle ids of apps allowed to use the key.
   * Example: 'com.companyname.productname.appname'
   * </pre>
   *
   * <code>repeated string allowed_bundle_ids = 1;</code>
   * @return The count of allowedBundleIds.
   */
  int getAllowedBundleIdsCount();
  /**
   * <pre>
   * iOS bundle ids of apps allowed to use the key.
   * Example: 'com.companyname.productname.appname'
   * </pre>
   *
   * <code>repeated string allowed_bundle_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The allowedBundleIds at the given index.
   */
  java.lang.String getAllowedBundleIds(int index);
  /**
   * <pre>
   * iOS bundle ids of apps allowed to use the key.
   * Example: 'com.companyname.productname.appname'
   * </pre>
   *
   * <code>repeated string allowed_bundle_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedBundleIds at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedBundleIdsBytes(int index);
}
