// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/recaptchaenterprise/v1/recaptchaenterprise.proto

package com.google.recaptchaenterprise.v1;

public final class RecaptchaEnterpriseProto {
  private RecaptchaEnterpriseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_CreateAssessmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_CreateAssessmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_Assessment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_Assessment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_RiskAnalysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_RiskAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_TokenProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_TokenProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_AccountDefenderAssessment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_AccountDefenderAssessment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_CreateKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_CreateKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListKeysRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListKeysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_GetKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_GetKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_UpdateKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_UpdateKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_DeleteKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_DeleteKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_MigrateKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_MigrateKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_GetMetricsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_GetMetricsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_Metrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_Metrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_Key_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_Key_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_TestingOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_TestingOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_WebKeySettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_WebKeySettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_AndroidKeySettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_AndroidKeySettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_IOSKeySettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_IOSKeySettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_ScoreBucketsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_ScoreBucketsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_ActionMetricsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_ActionMetricsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ChallengeMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ChallengeMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroupMembership_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroupMembership_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_recaptchaenterprise_v1_WafSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_recaptchaenterprise_v1_WafSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=google/cloud/recaptchaenterprise/v1/re" +
      "captchaenterprise.proto\022#google.cloud.re" +
      "captchaenterprise.v1\032\034google/api/annotat" +
      "ions.proto\032\027google/api/client.proto\032\037goo" +
      "gle/api/field_behavior.proto\032\031google/api" +
      "/resource.proto\032\033google/protobuf/empty.p" +
      "roto\032 google/protobuf/field_mask.proto\032\037" +
      "google/protobuf/timestamp.proto\"\250\001\n\027Crea" +
      "teAssessmentRequest\022C\n\006parent\030\001 \001(\tB3\340A\002" +
      "\372A-\n+cloudresourcemanager.googleapis.com" +
      "/Project\022H\n\nassessment\030\002 \001(\0132/.google.cl" +
      "oud.recaptchaenterprise.v1.AssessmentB\003\340" +
      "A\002\"\260\005\n\031AnnotateAssessmentRequest\022C\n\004name" +
      "\030\001 \001(\tB5\340A\002\372A/\n-recaptchaenterprise.goog" +
      "leapis.com/Assessment\022b\n\nannotation\030\002 \001(" +
      "\0162I.google.cloud.recaptchaenterprise.v1." +
      "AnnotateAssessmentRequest.AnnotationB\003\340A" +
      "\001\022[\n\007reasons\030\003 \003(\0162E.google.cloud.recapt" +
      "chaenterprise.v1.AnnotateAssessmentReque" +
      "st.ReasonB\003\340A\001\022\036\n\021hashed_account_id\030\004 \001(" +
      "\014B\003\340A\001\"~\n\nAnnotation\022\032\n\026ANNOTATION_UNSPE" +
      "CIFIED\020\000\022\016\n\nLEGITIMATE\020\001\022\016\n\nFRAUDULENT\020\002" +
      "\022\030\n\020PASSWORD_CORRECT\020\003\032\002\010\001\022\032\n\022PASSWORD_I" +
      "NCORRECT\020\004\032\002\010\001\"\354\001\n\006Reason\022\026\n\022REASON_UNSP" +
      "ECIFIED\020\000\022\016\n\nCHARGEBACK\020\001\022\024\n\020CHARGEBACK_" +
      "FRAUD\020\010\022\026\n\022CHARGEBACK_DISPUTE\020\t\022\026\n\022PAYME" +
      "NT_HEURISTICS\020\002\022\030\n\024INITIATED_TWO_FACTOR\020" +
      "\007\022\025\n\021PASSED_TWO_FACTOR\020\003\022\025\n\021FAILED_TWO_F" +
      "ACTOR\020\004\022\024\n\020CORRECT_PASSWORD\020\005\022\026\n\022INCORRE" +
      "CT_PASSWORD\020\006\"\034\n\032AnnotateAssessmentRespo" +
      "nse\"\304\003\n\nAssessment\022\021\n\004name\030\001 \001(\tB\003\340A\003\0229\n" +
      "\005event\030\002 \001(\0132*.google.cloud.recaptchaent" +
      "erprise.v1.Event\022M\n\rrisk_analysis\030\003 \001(\0132" +
      "1.google.cloud.recaptchaenterprise.v1.Ri" +
      "skAnalysisB\003\340A\003\022S\n\020token_properties\030\004 \001(" +
      "\01324.google.cloud.recaptchaenterprise.v1." +
      "TokenPropertiesB\003\340A\003\022c\n\033account_defender" +
      "_assessment\030\006 \001(\0132>.google.cloud.recaptc" +
      "haenterprise.v1.AccountDefenderAssessmen" +
      "t:_\352A\\\n-recaptchaenterprise.googleapis.c" +
      "om/Assessment\022+projects/{project}/assess" +
      "ments/{assessment}\"\247\001\n\005Event\022\022\n\005token\030\001 " +
      "\001(\tB\003\340A\001\022\025\n\010site_key\030\002 \001(\tB\003\340A\001\022\027\n\nuser_" +
      "agent\030\003 \001(\tB\003\340A\001\022\034\n\017user_ip_address\030\004 \001(" +
      "\tB\003\340A\001\022\034\n\017expected_action\030\005 \001(\tB\003\340A\001\022\036\n\021" +
      "hashed_account_id\030\006 \001(\014B\003\340A\001\"\261\002\n\014RiskAna" +
      "lysis\022\r\n\005score\030\001 \001(\002\022W\n\007reasons\030\002 \003(\0162F." +
      "google.cloud.recaptchaenterprise.v1.Risk" +
      "Analysis.ClassificationReason\"\270\001\n\024Classi" +
      "ficationReason\022%\n!CLASSIFICATION_REASON_" +
      "UNSPECIFIED\020\000\022\016\n\nAUTOMATION\020\001\022\032\n\026UNEXPEC" +
      "TED_ENVIRONMENT\020\002\022\024\n\020TOO_MUCH_TRAFFIC\020\003\022" +
      "\035\n\031UNEXPECTED_USAGE_PATTERNS\020\004\022\030\n\024LOW_CO" +
      "NFIDENCE_SCORE\020\005\"\343\002\n\017TokenProperties\022\r\n\005" +
      "valid\030\001 \001(\010\022Z\n\016invalid_reason\030\002 \001(\0162B.go" +
      "ogle.cloud.recaptchaenterprise.v1.TokenP" +
      "roperties.InvalidReason\022/\n\013create_time\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\022\020\n\010host" +
      "name\030\004 \001(\t\022\016\n\006action\030\005 \001(\t\"\221\001\n\rInvalidRe" +
      "ason\022\036\n\032INVALID_REASON_UNSPECIFIED\020\000\022\032\n\026" +
      "UNKNOWN_INVALID_REASON\020\001\022\r\n\tMALFORMED\020\002\022" +
      "\013\n\007EXPIRED\020\003\022\010\n\004DUPE\020\004\022\013\n\007MISSING\020\005\022\021\n\rB" +
      "ROWSER_ERROR\020\006\"\266\002\n\031AccountDefenderAssess" +
      "ment\022c\n\006labels\030\001 \003(\0162S.google.cloud.reca" +
      "ptchaenterprise.v1.AccountDefenderAssess" +
      "ment.AccountDefenderLabel\"\263\001\n\024AccountDef" +
      "enderLabel\022&\n\"ACCOUNT_DEFENDER_LABEL_UNS" +
      "PECIFIED\020\000\022\021\n\rPROFILE_MATCH\020\001\022\035\n\031SUSPICI" +
      "OUS_LOGIN_ACTIVITY\020\002\022\037\n\033SUSPICIOUS_ACCOU" +
      "NT_CREATION\020\003\022 \n\034RELATED_ACCOUNTS_NUMBER" +
      "_HIGH\020\004\"\223\001\n\020CreateKeyRequest\022C\n\006parent\030\001" +
      " \001(\tB3\340A\002\372A-\n+cloudresourcemanager.googl" +
      "eapis.com/Project\022:\n\003key\030\002 \001(\0132(.google." +
      "cloud.recaptchaenterprise.v1.KeyB\003\340A\002\"\207\001" +
      "\n\017ListKeysRequest\022C\n\006parent\030\001 \001(\tB3\340A\002\372A" +
      "-\n+cloudresourcemanager.googleapis.com/P" +
      "roject\022\026\n\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\npage_t" +
      "oken\030\003 \001(\tB\003\340A\001\"c\n\020ListKeysResponse\0226\n\004k" +
      "eys\030\001 \003(\0132(.google.cloud.recaptchaenterp" +
      "rise.v1.Key\022\027\n\017next_page_token\030\002 \001(\t\"M\n\r" +
      "GetKeyRequest\022<\n\004name\030\001 \001(\tB.\340A\002\372A(\n&rec" +
      "aptchaenterprise.googleapis.com/Key\"\204\001\n\020" +
      "UpdateKeyRequest\022:\n\003key\030\001 \001(\0132(.google.c" +
      "loud.recaptchaenterprise.v1.KeyB\003\340A\002\0224\n\013" +
      "update_mask\030\002 \001(\0132\032.google.protobuf.Fiel" +
      "dMaskB\003\340A\001\"P\n\020DeleteKeyRequest\022<\n\004name\030\001" +
      " \001(\tB.\340A\002\372A(\n&recaptchaenterprise.google" +
      "apis.com/Key\"Q\n\021MigrateKeyRequest\022<\n\004nam" +
      "e\030\001 \001(\tB.\340A\002\372A(\n&recaptchaenterprise.goo" +
      "gleapis.com/Key\"U\n\021GetMetricsRequest\022@\n\004" +
      "name\030\001 \001(\tB2\340A\002\372A,\n*recaptchaenterprise." +
      "googleapis.com/Metrics\"\300\002\n\007Metrics\022\021\n\004na" +
      "me\030\004 \001(\tB\003\340A\003\022.\n\nstart_time\030\001 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022H\n\rscore_metrics\030\002" +
      " \003(\01321.google.cloud.recaptchaenterprise." +
      "v1.ScoreMetrics\022P\n\021challenge_metrics\030\003 \003" +
      "(\01325.google.cloud.recaptchaenterprise.v1" +
      ".ChallengeMetrics:V\352AS\n*recaptchaenterpr" +
      "ise.googleapis.com/Metrics\022%projects/{pr" +
      "oject}/keys/{key}/metrics\"\265\005\n\003Key\022\014\n\004nam" +
      "e\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022K\n\014web_set" +
      "tings\030\003 \001(\01323.google.cloud.recaptchaente" +
      "rprise.v1.WebKeySettingsH\000\022S\n\020android_se" +
      "ttings\030\004 \001(\01327.google.cloud.recaptchaent" +
      "erprise.v1.AndroidKeySettingsH\000\022K\n\014ios_s" +
      "ettings\030\005 \001(\01323.google.cloud.recaptchaen" +
      "terprise.v1.IOSKeySettingsH\000\022D\n\006labels\030\006" +
      " \003(\01324.google.cloud.recaptchaenterprise." +
      "v1.Key.LabelsEntry\022/\n\013create_time\030\007 \001(\0132" +
      "\032.google.protobuf.Timestamp\022L\n\017testing_o" +
      "ptions\030\t \001(\01323.google.cloud.recaptchaent" +
      "erprise.v1.TestingOptions\022F\n\014waf_setting" +
      "s\030\n \001(\01320.google.cloud.recaptchaenterpri" +
      "se.v1.WafSettings\032-\n\013LabelsEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:J\352AG\n&recaptcha" +
      "enterprise.googleapis.com/Key\022\035projects/" +
      "{project}/keys/{key}B\023\n\021platform_setting" +
      "s\"\350\001\n\016TestingOptions\022\025\n\rtesting_score\030\001 " +
      "\001(\002\022_\n\021testing_challenge\030\002 \001(\0162D.google." +
      "cloud.recaptchaenterprise.v1.TestingOpti" +
      "ons.TestingChallenge\"^\n\020TestingChallenge" +
      "\022!\n\035TESTING_CHALLENGE_UNSPECIFIED\020\000\022\r\n\tN" +
      "OCAPTCHA\020\001\022\030\n\024UNSOLVABLE_CHALLENGE\020\002\"\220\004\n" +
      "\016WebKeySettings\022\031\n\021allow_all_domains\030\003 \001" +
      "(\010\022\027\n\017allowed_domains\030\001 \003(\t\022\031\n\021allow_amp" +
      "_traffic\030\002 \001(\010\022b\n\020integration_type\030\004 \001(\016" +
      "2C.google.cloud.recaptchaenterprise.v1.W" +
      "ebKeySettings.IntegrationTypeB\003\340A\002\022v\n\035ch" +
      "allenge_security_preference\030\005 \001(\0162O.goog" +
      "le.cloud.recaptchaenterprise.v1.WebKeySe" +
      "ttings.ChallengeSecurityPreference\"[\n\017In" +
      "tegrationType\022 \n\034INTEGRATION_TYPE_UNSPEC" +
      "IFIED\020\000\022\t\n\005SCORE\020\001\022\014\n\010CHECKBOX\020\002\022\r\n\tINVI" +
      "SIBLE\020\003\"v\n\033ChallengeSecurityPreference\022-" +
      "\n)CHALLENGE_SECURITY_PREFERENCE_UNSPECIF" +
      "IED\020\000\022\r\n\tUSABILITY\020\001\022\013\n\007BALANCE\020\002\022\014\n\010SEC" +
      "URITY\020\003\"T\n\022AndroidKeySettings\022\037\n\027allow_a" +
      "ll_package_names\030\002 \001(\010\022\035\n\025allowed_packag" +
      "e_names\030\001 \003(\t\"J\n\016IOSKeySettings\022\034\n\024allow" +
      "_all_bundle_ids\030\002 \001(\010\022\032\n\022allowed_bundle_" +
      "ids\030\001 \003(\t\"\251\001\n\021ScoreDistribution\022_\n\rscore" +
      "_buckets\030\001 \003(\0132H.google.cloud.recaptchae" +
      "nterprise.v1.ScoreDistribution.ScoreBuck" +
      "etsEntry\0323\n\021ScoreBucketsEntry\022\013\n\003key\030\001 \001" +
      "(\005\022\r\n\005value\030\002 \001(\003:\0028\001\"\253\002\n\014ScoreMetrics\022O" +
      "\n\017overall_metrics\030\001 \001(\01326.google.cloud.r" +
      "ecaptchaenterprise.v1.ScoreDistribution\022" +
      "\\\n\016action_metrics\030\002 \003(\0132D.google.cloud.r" +
      "ecaptchaenterprise.v1.ScoreMetrics.Actio" +
      "nMetricsEntry\032l\n\022ActionMetricsEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022E\n\005value\030\002 \001(\01326.google.cloud.r" +
      "ecaptchaenterprise.v1.ScoreDistribution:" +
      "\0028\001\"o\n\020ChallengeMetrics\022\026\n\016pageload_coun" +
      "t\030\001 \001(\003\022\027\n\017nocaptcha_count\030\002 \001(\003\022\024\n\014fail" +
      "ed_count\030\003 \001(\003\022\024\n\014passed_count\030\004 \001(\003\"\266\001\n" +
      ")ListRelatedAccountGroupMembershipsReque" +
      "st\022X\n\006parent\030\001 \001(\tBH\340A\002\372AB\022@recaptchaent" +
      "erprise.googleapis.com/RelatedAccountGro" +
      "upMembership\022\026\n\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\n" +
      "page_token\030\003 \001(\tB\003\340A\001\"\264\001\n*ListRelatedAcc" +
      "ountGroupMembershipsResponse\022m\n!related_" +
      "account_group_memberships\030\001 \003(\0132B.google" +
      ".cloud.recaptchaenterprise.v1.RelatedAcc" +
      "ountGroupMembership\022\027\n\017next_page_token\030\002" +
      " \001(\t\"\242\001\n\037ListRelatedAccountGroupsRequest" +
      "\022N\n\006parent\030\001 \001(\tB>\340A\002\372A8\0226recaptchaenter" +
      "prise.googleapis.com/RelatedAccountGroup" +
      "\022\026\n\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\npage_token\030\003" +
      " \001(\tB\003\340A\001\"\225\001\n ListRelatedAccountGroupsRe" +
      "sponse\022X\n\026related_account_groups\030\001 \003(\01328" +
      ".google.cloud.recaptchaenterprise.v1.Rel" +
      "atedAccountGroup\022\027\n\017next_page_token\030\002 \001(" +
      "\t\"\331\001\n+SearchRelatedAccountGroupMembershi" +
      "psRequest\022Y\n\007project\030\001 \001(\tBH\340A\002\372AB\022@reca" +
      "ptchaenterprise.googleapis.com/RelatedAc" +
      "countGroupMembership\022\036\n\021hashed_account_i" +
      "d\030\002 \001(\014B\003\340A\001\022\026\n\tpage_size\030\003 \001(\005B\003\340A\001\022\027\n\n" +
      "page_token\030\004 \001(\tB\003\340A\001\"\266\001\n,SearchRelatedA" +
      "ccountGroupMembershipsResponse\022m\n!relate" +
      "d_account_group_memberships\030\001 \003(\0132B.goog" +
      "le.cloud.recaptchaenterprise.v1.RelatedA" +
      "ccountGroupMembership\022\027\n\017next_page_token" +
      "\030\002 \001(\t\"\263\002\n\035RelatedAccountGroupMembership" +
      "\022V\n\004name\030\001 \001(\tBH\340A\002\372AB\n@recaptchaenterpr" +
      "ise.googleapis.com/RelatedAccountGroupMe" +
      "mbership\022\031\n\021hashed_account_id\030\002 \001(\014:\236\001\352A" +
      "\232\001\n@recaptchaenterprise.googleapis.com/R" +
      "elatedAccountGroupMembership\022Vprojects/{" +
      "project}/relatedaccountgroups/{relatedac" +
      "countgroup}/memberships/{membership}\"\337\001\n" +
      "\023RelatedAccountGroup\022L\n\004name\030\001 \001(\tB>\340A\002\372" +
      "A8\n6recaptchaenterprise.googleapis.com/R" +
      "elatedAccountGroup:z\352Aw\n6recaptchaenterp" +
      "rise.googleapis.com/RelatedAccountGroup\022" +
      "=projects/{project}/relatedaccountgroups" +
      "/{relatedaccountgroup}\"\322\002\n\013WafSettings\022U" +
      "\n\013waf_service\030\001 \001(\0162;.google.cloud.recap" +
      "tchaenterprise.v1.WafSettings.WafService" +
      "B\003\340A\002\022U\n\013waf_feature\030\002 \001(\0162;.google.clou" +
      "d.recaptchaenterprise.v1.WafSettings.Waf" +
      "FeatureB\003\340A\002\"b\n\nWafFeature\022\033\n\027WAF_FEATUR" +
      "E_UNSPECIFIED\020\000\022\022\n\016CHALLENGE_PAGE\020\001\022\021\n\rS" +
      "ESSION_TOKEN\020\002\022\020\n\014ACTION_TOKEN\020\003\"1\n\nWafS" +
      "ervice\022\033\n\027WAF_SERVICE_UNSPECIFIED\020\000\022\006\n\002C" +
      "A\020\0012\221\023\n\032RecaptchaEnterpriseService\022\316\001\n\020C" +
      "reateAssessment\022<.google.cloud.recaptcha" +
      "enterprise.v1.CreateAssessmentRequest\032/." +
      "google.cloud.recaptchaenterprise.v1.Asse" +
      "ssment\"K\202\323\344\223\0021\"#/v1/{parent=projects/*}/" +
      "assessments:\nassessment\332A\021parent,assessm" +
      "ent\022\340\001\n\022AnnotateAssessment\022>.google.clou" +
      "d.recaptchaenterprise.v1.AnnotateAssessm" +
      "entRequest\032?.google.cloud.recaptchaenter" +
      "prise.v1.AnnotateAssessmentResponse\"I\202\323\344" +
      "\223\0021\",/v1/{name=projects/*/assessments/*}" +
      ":annotate:\001*\332A\017name,annotation\022\227\001\n\tCreat" +
      "eKey\0225.google.cloud.recaptchaenterprise." +
      "v1.CreateKeyRequest\032(.google.cloud.recap" +
      "tchaenterprise.v1.Key\")\202\323\344\223\002#\"\034/v1/{pare" +
      "nt=projects/*}/keys:\003key\022\235\001\n\010ListKeys\0224." +
      "google.cloud.recaptchaenterprise.v1.List" +
      "KeysRequest\0325.google.cloud.recaptchaente" +
      "rprise.v1.ListKeysResponse\"$\202\323\344\223\002\036\022\034/v1/" +
      "{parent=projects/*}/keys\022\214\001\n\006GetKey\0222.go" +
      "ogle.cloud.recaptchaenterprise.v1.GetKey" +
      "Request\032(.google.cloud.recaptchaenterpri" +
      "se.v1.Key\"$\202\323\344\223\002\036\022\034/v1/{name=projects/*/" +
      "keys/*}\022\233\001\n\tUpdateKey\0225.google.cloud.rec" +
      "aptchaenterprise.v1.UpdateKeyRequest\032(.g" +
      "oogle.cloud.recaptchaenterprise.v1.Key\"-" +
      "\202\323\344\223\002\'2 /v1/{key.name=projects/*/keys/*}" +
      ":\003key\022\200\001\n\tDeleteKey\0225.google.cloud.recap" +
      "tchaenterprise.v1.DeleteKeyRequest\032\026.goo" +
      "gle.protobuf.Empty\"$\202\323\344\223\002\036*\034/v1/{name=pr" +
      "ojects/*/keys/*}\022\237\001\n\nMigrateKey\0226.google" +
      ".cloud.recaptchaenterprise.v1.MigrateKey" +
      "Request\032(.google.cloud.recaptchaenterpri" +
      "se.v1.Key\"/\202\323\344\223\002)\"$/v1/{name=projects/*/" +
      "keys/*}:migrate:\001*\022\247\001\n\nGetMetrics\0226.goog" +
      "le.cloud.recaptchaenterprise.v1.GetMetri" +
      "csRequest\032,.google.cloud.recaptchaenterp" +
      "rise.v1.Metrics\"3\202\323\344\223\002&\022$/v1/{name=proje" +
      "cts/*/keys/*/metrics}\332A\004name\022\346\001\n\030ListRel" +
      "atedAccountGroups\022D.google.cloud.recaptc" +
      "haenterprise.v1.ListRelatedAccountGroups" +
      "Request\032E.google.cloud.recaptchaenterpri" +
      "se.v1.ListRelatedAccountGroupsResponse\"=" +
      "\202\323\344\223\002.\022,/v1/{parent=projects/*}/relateda" +
      "ccountgroups\332A\006parent\022\222\002\n\"ListRelatedAcc" +
      "ountGroupMemberships\022N.google.cloud.reca" +
      "ptchaenterprise.v1.ListRelatedAccountGro" +
      "upMembershipsRequest\032O.google.cloud.reca" +
      "ptchaenterprise.v1.ListRelatedAccountGro" +
      "upMembershipsResponse\"K\202\323\344\223\002<\022:/v1/{pare" +
      "nt=projects/*/relatedaccountgroups/*}/me" +
      "mberships\332A\006parent\022\262\002\n$SearchRelatedAcco" +
      "untGroupMemberships\022P.google.cloud.recap" +
      "tchaenterprise.v1.SearchRelatedAccountGr" +
      "oupMembershipsRequest\032Q.google.cloud.rec" +
      "aptchaenterprise.v1.SearchRelatedAccount" +
      "GroupMembershipsResponse\"e\202\323\344\223\002C\">/v1/{p" +
      "roject=projects/*}/relatedaccountgroupme" +
      "mberships:search:\001*\332A\031project,hashed_acc" +
      "ount_id\032V\312A\"recaptchaenterprise.googleap" +
      "is.com\322A.https://www.googleapis.com/auth" +
      "/cloud-platformB\223\002\n!com.google.recaptcha" +
      "enterprise.v1B\030RecaptchaEnterpriseProtoP" +
      "\001ZVgoogle.golang.org/genproto/googleapis" +
      "/cloud/recaptchaenterprise/v1;recaptchae" +
      "nterprise\242\002\004GCRE\252\002#Google.Cloud.Recaptch" +
      "aEnterprise.V1\312\002#Google\\Cloud\\RecaptchaE" +
      "nterprise\\V1\352\002&Google::Cloud::RecaptchaE" +
      "nterprise::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_cloud_recaptchaenterprise_v1_CreateAssessmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_recaptchaenterprise_v1_CreateAssessmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_CreateAssessmentRequest_descriptor,
        new java.lang.String[] { "Parent", "Assessment", });
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentRequest_descriptor,
        new java.lang.String[] { "Name", "Annotation", "Reasons", "HashedAccountId", });
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_AnnotateAssessmentResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_recaptchaenterprise_v1_Assessment_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_recaptchaenterprise_v1_Assessment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_Assessment_descriptor,
        new java.lang.String[] { "Name", "Event", "RiskAnalysis", "TokenProperties", "AccountDefenderAssessment", });
    internal_static_google_cloud_recaptchaenterprise_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_recaptchaenterprise_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_Event_descriptor,
        new java.lang.String[] { "Token", "SiteKey", "UserAgent", "UserIpAddress", "ExpectedAction", "HashedAccountId", });
    internal_static_google_cloud_recaptchaenterprise_v1_RiskAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_recaptchaenterprise_v1_RiskAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_RiskAnalysis_descriptor,
        new java.lang.String[] { "Score", "Reasons", });
    internal_static_google_cloud_recaptchaenterprise_v1_TokenProperties_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_recaptchaenterprise_v1_TokenProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_TokenProperties_descriptor,
        new java.lang.String[] { "Valid", "InvalidReason", "CreateTime", "Hostname", "Action", });
    internal_static_google_cloud_recaptchaenterprise_v1_AccountDefenderAssessment_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_recaptchaenterprise_v1_AccountDefenderAssessment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_AccountDefenderAssessment_descriptor,
        new java.lang.String[] { "Labels", });
    internal_static_google_cloud_recaptchaenterprise_v1_CreateKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_recaptchaenterprise_v1_CreateKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_CreateKeyRequest_descriptor,
        new java.lang.String[] { "Parent", "Key", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListKeysRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_recaptchaenterprise_v1_ListKeysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListKeysResponse_descriptor,
        new java.lang.String[] { "Keys", "NextPageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_GetKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_recaptchaenterprise_v1_GetKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_GetKeyRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_recaptchaenterprise_v1_UpdateKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_recaptchaenterprise_v1_UpdateKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_UpdateKeyRequest_descriptor,
        new java.lang.String[] { "Key", "UpdateMask", });
    internal_static_google_cloud_recaptchaenterprise_v1_DeleteKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_recaptchaenterprise_v1_DeleteKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_DeleteKeyRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_recaptchaenterprise_v1_MigrateKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_recaptchaenterprise_v1_MigrateKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_MigrateKeyRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_recaptchaenterprise_v1_GetMetricsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_recaptchaenterprise_v1_GetMetricsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_GetMetricsRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_recaptchaenterprise_v1_Metrics_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_recaptchaenterprise_v1_Metrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_Metrics_descriptor,
        new java.lang.String[] { "Name", "StartTime", "ScoreMetrics", "ChallengeMetrics", });
    internal_static_google_cloud_recaptchaenterprise_v1_Key_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_recaptchaenterprise_v1_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_Key_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "WebSettings", "AndroidSettings", "IosSettings", "Labels", "CreateTime", "TestingOptions", "WafSettings", "PlatformSettings", });
    internal_static_google_cloud_recaptchaenterprise_v1_Key_LabelsEntry_descriptor =
      internal_static_google_cloud_recaptchaenterprise_v1_Key_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_recaptchaenterprise_v1_Key_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_Key_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_recaptchaenterprise_v1_TestingOptions_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_recaptchaenterprise_v1_TestingOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_TestingOptions_descriptor,
        new java.lang.String[] { "TestingScore", "TestingChallenge", });
    internal_static_google_cloud_recaptchaenterprise_v1_WebKeySettings_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_recaptchaenterprise_v1_WebKeySettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_WebKeySettings_descriptor,
        new java.lang.String[] { "AllowAllDomains", "AllowedDomains", "AllowAmpTraffic", "IntegrationType", "ChallengeSecurityPreference", });
    internal_static_google_cloud_recaptchaenterprise_v1_AndroidKeySettings_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_recaptchaenterprise_v1_AndroidKeySettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_AndroidKeySettings_descriptor,
        new java.lang.String[] { "AllowAllPackageNames", "AllowedPackageNames", });
    internal_static_google_cloud_recaptchaenterprise_v1_IOSKeySettings_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_recaptchaenterprise_v1_IOSKeySettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_IOSKeySettings_descriptor,
        new java.lang.String[] { "AllowAllBundleIds", "AllowedBundleIds", });
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_descriptor,
        new java.lang.String[] { "ScoreBuckets", });
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_ScoreBucketsEntry_descriptor =
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_ScoreBucketsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ScoreDistribution_ScoreBucketsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_descriptor,
        new java.lang.String[] { "OverallMetrics", "ActionMetrics", });
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_ActionMetricsEntry_descriptor =
      internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_ActionMetricsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ScoreMetrics_ActionMetricsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_recaptchaenterprise_v1_ChallengeMetrics_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_recaptchaenterprise_v1_ChallengeMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ChallengeMetrics_descriptor,
        new java.lang.String[] { "PageloadCount", "NocaptchaCount", "FailedCount", "PassedCount", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupMembershipsResponse_descriptor,
        new java.lang.String[] { "RelatedAccountGroupMemberships", "NextPageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_ListRelatedAccountGroupsResponse_descriptor,
        new java.lang.String[] { "RelatedAccountGroups", "NextPageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsRequest_descriptor,
        new java.lang.String[] { "Project", "HashedAccountId", "PageSize", "PageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_SearchRelatedAccountGroupMembershipsResponse_descriptor,
        new java.lang.String[] { "RelatedAccountGroupMemberships", "NextPageToken", });
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroupMembership_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroupMembership_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroupMembership_descriptor,
        new java.lang.String[] { "Name", "HashedAccountId", });
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroup_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_RelatedAccountGroup_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_recaptchaenterprise_v1_WafSettings_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_google_cloud_recaptchaenterprise_v1_WafSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_recaptchaenterprise_v1_WafSettings_descriptor,
        new java.lang.String[] { "WafService", "WafFeature", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
